version: 2

builds:
  - id: streamsh
    main: ./cmd/streamsh
    binary: streamsh
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: streamshd
    main: ./cmd/streamshd
    binary: streamshd
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds:
      - streamsh
      - streamshd
    format: tar.gz
    name_template: "streamsh_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
